### ISSUE TITLE
llua_do_call

### ISSUE THREAD

**Issue by FL3SH** [JPvRiel/conky-seamod#3] opened 2016-09-01 17:58 UTC
I followed you guide and got this:
Conky: llua_do_call: function conky_main execution failed: attempt to call a nil value

https://imgur.com/a/Hz9hI

**Comment by JPvRiel** [comment] 2016-09-02 09:31
Ouch, okay, maybe it's missing dependencies. A bit more info please:
- distro/gnome version and conky version
- which conky package installed? E.g. if Ubuntu `conky-all`?

Please run

```
$ conky -v
```

Also, if debian/ubuntu

```
$ dpkg-query --list conky*
```

**Comment by JPvRiel** [comment] 2016-11-26 14:33
I'll close this as "wontfix" in a while if more info about dependencies isn't confirmed. I suppose an enhancement might be to have conky check for the needed dependency and display an error (but that should rather be done upstream in the conky project?).

**Comment by JPvRiel** [comment] 2017-09-09 16:55
Been unable to reproduce - seems fine on two of my Ubuntu 16.04 systems.

**Closed as completed by JPvRiel** 2017-09-09 16:55 UTC
Labels: wontfix
